/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TicketsOrderIdRouteImport } from './routes/tickets.$orderId'
import { Route as MoviesMovieCodeRouteImport } from './routes/movies.$movieCode'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as BookingShowtimeIdRouteImport } from './routes/booking.$showtimeId'
import { Route as AdminRoomsRoomIdLayoutRouteImport } from './routes/admin.rooms.$roomId.layout'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TicketsOrderIdRoute = TicketsOrderIdRouteImport.update({
  id: '/tickets/$orderId',
  path: '/tickets/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieCodeRoute = MoviesMovieCodeRouteImport.update({
  id: '/movies/$movieCode',
  path: '/movies/$movieCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingShowtimeIdRoute = BookingShowtimeIdRouteImport.update({
  id: '/booking/$showtimeId',
  path: '/booking/$showtimeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoomIdLayoutRoute = AdminRoomsRoomIdLayoutRouteImport.update({
  id: '/rooms/$roomId/layout',
  path: '/rooms/$roomId/layout',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/movies/$movieCode': typeof MoviesMovieCodeRoute
  '/tickets/$orderId': typeof TicketsOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rooms/$roomId/layout': typeof AdminRoomsRoomIdLayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/movies/$movieCode': typeof MoviesMovieCodeRoute
  '/tickets/$orderId': typeof TicketsOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/rooms/$roomId/layout': typeof AdminRoomsRoomIdLayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/movies/$movieCode': typeof MoviesMovieCodeRoute
  '/tickets/$orderId': typeof TicketsOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rooms/$roomId/layout': typeof AdminRoomsRoomIdLayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking/$showtimeId'
    | '/checkout/$orderId'
    | '/movies/$movieCode'
    | '/tickets/$orderId'
    | '/admin/'
    | '/admin/rooms/$roomId/layout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking/$showtimeId'
    | '/checkout/$orderId'
    | '/movies/$movieCode'
    | '/tickets/$orderId'
    | '/admin'
    | '/admin/rooms/$roomId/layout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking/$showtimeId'
    | '/checkout/$orderId'
    | '/movies/$movieCode'
    | '/tickets/$orderId'
    | '/admin/'
    | '/admin/rooms/$roomId/layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingShowtimeIdRoute: typeof BookingShowtimeIdRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  MoviesMovieCodeRoute: typeof MoviesMovieCodeRoute
  TicketsOrderIdRoute: typeof TicketsOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tickets/$orderId': {
      id: '/tickets/$orderId'
      path: '/tickets/$orderId'
      fullPath: '/tickets/$orderId'
      preLoaderRoute: typeof TicketsOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieCode': {
      id: '/movies/$movieCode'
      path: '/movies/$movieCode'
      fullPath: '/movies/$movieCode'
      preLoaderRoute: typeof MoviesMovieCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$showtimeId': {
      id: '/booking/$showtimeId'
      path: '/booking/$showtimeId'
      fullPath: '/booking/$showtimeId'
      preLoaderRoute: typeof BookingShowtimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms/$roomId/layout': {
      id: '/admin/rooms/$roomId/layout'
      path: '/rooms/$roomId/layout'
      fullPath: '/admin/rooms/$roomId/layout'
      preLoaderRoute: typeof AdminRoomsRoomIdLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRoomsRoomIdLayoutRoute: typeof AdminRoomsRoomIdLayoutRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRoomsRoomIdLayoutRoute: AdminRoomsRoomIdLayoutRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingShowtimeIdRoute: BookingShowtimeIdRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  MoviesMovieCodeRoute: MoviesMovieCodeRoute,
  TicketsOrderIdRoute: TicketsOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
